options:
  logging: CLOUD_LOGGING_ONLY

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/mmm-app:$BUILD_ID
      - -t
      - gcr.io/$PROJECT_ID/mmm-app:latest
      - .

  # Step 2: Push the image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/mmm-app:$BUILD_ID

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - mmm-app
      - --image=gcr.io/$PROJECT_ID/mmm-app:$BUILD_ID
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8501
      - --memory=2Gi
      - --cpu=1
      - --timeout=3600
      - --max-instances=10
      - --set-env-vars=STREAMLIT_SERVER_PORT=8501,STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - --update-secrets=/app/.streamlit/config.toml=marketing-app-config:latest
      - --update-secrets=/app/.streamlit/secrets.toml=marketing-app-secrets:latest

timeout: 1200s

# Substitutions for flexibility
substitutions:
  _SERVICE_NAME: mmm-app
  _REGION: us-central1
  _PROJECT_ID: eia-livingston-southeastern

timeout: 1200s

# Substitutions for flexibility
substitutions:
  _SERVICE_NAME: mmm-app
  _REGION: us-central1
  _PROJECT_ID: eia-livingston-southeastern