name: streamlit-MMM
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip

  # core data & viz libs (from your requirements.txt)
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - shap=0.47.1
  - plotly=5.24.1
  - streamlit=1.44.1
  - pillow=11.1.0
  - requests=2.32.3
  - scipy=1.13.0
  - openpyxl
  - tabulate # ← new, for DataFrame.to_markdown()

  # use pip to install the rest (gdown, fredapi, GenAI SDKs, LangChain)
  - pip:
      - gdown==5.2.0
      - fredapi==0.5.2
      - google-genai
      - langchain-google-genai
      - langchain # ← new, core LangChain library
